# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c27f4b31522b2469017884dc414471faf29af3f3fae30e6caa53b6f912af71cf5050f7f0654a9485ff74f55ed08be73e0ed1fdb7a3e6cddc43da4456aae129c

test:
  secret_key_base: 0548fab2f0aa0b4f8459868e7eabc6a2c5cd9f71e7ce29a5bc386a52b22254505f9b728bbef33b454cf2ee1d77a39e1892c090c836352fa47f71fb9cfd198dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
